Repository dfirtrack/dfirtrack, pull requests merged in 2021-05, with the labels that each got.

#93 Api update
  dfirtrack_api/openapi/openapi_dfirtrack.yml
  dfirtrack_api/serializers/dfirtrack_artifacts.py
  dfirtrack_api/serializers/dfirtrack_artifacts_fk.py
  dfirtrack_api/serializers/dfirtrack_main.py
  dfirtrack_api/serializers/dfirtrack_main_fk.py
  dfirtrack_api/tests/dfirtrack_artifacts/artifact/test_artifact_api_views.py
  dfirtrack_api/tests/dfirtrack_artifacts/artifactpriority/__init__.py
  dfirtrack_api/tests/dfirtrack_artifacts/artifactpriority/test_artifactpriority_api_views.py
  dfirtrack_api/tests/dfirtrack_main/case/test_case_api_views.py
  dfirtrack_api/tests/dfirtrack_main/casepriority/__init__.py
  dfirtrack_api/tests/dfirtrack_main/casepriority/test_casepriority_api_views.py
  dfirtrack_api/tests/dfirtrack_main/casestatus/__init__.py
  dfirtrack_api/tests/dfirtrack_main/casestatus/test_casestatus_api_views.py
  dfirtrack_api/tests/dfirtrack_main/casetype/__init__.py
  dfirtrack_api/tests/dfirtrack_main/casetype/test_casetype_api_views.py
  dfirtrack_api/tests/dfirtrack_main/system/test_system_api_views.py
  dfirtrack_api/tests/dfirtrack_main/task/test_task_api_views.py
  dfirtrack_api/urls.py
  dfirtrack_api/views/dfirtrack_artifacts.py
  dfirtrack_api/views/dfirtrack_main.py
Labels: code, housekeeping

#91 Develop
  dfirtrack_main/async_messages/system_messages.py
  dfirtrack_main/modificator/system_modificator.py
  dfirtrack_main/templates/dfirtrack_main/system/system_modificator.html
  dfirtrack_main/tests/system/test_system_creator_views.py
  dfirtrack_main/tests/system/test_system_modificator_views.py
Labels: feature

#97 replace RunSQL with RunPython to avoid custom SQL and instead use ORM
  dfirtrack_artifacts/migrations/0002_default_values.py
  dfirtrack_artifacts/migrations/0005_values_artifactpriority.py
  dfirtrack_main/migrations/0002_default_values.py
  dfirtrack_main/migrations/0003_default_tags.py
  dfirtrack_main/migrations/0006_tagcolors.py
  dfirtrack_main/migrations/0007_systemstatus.py
  dfirtrack_main/migrations/0013_case_attributes_default_values.py
Labels: housekeeping
